//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploWCF
{
	using System.Runtime.Serialization;

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Usuarios", Namespace = "http://schemas.datacontract.org/2004/07/EjemploWCF")]
	public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject
	{
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
		private System.Nullable<bool> ActivoField;
		private string NombreField;
		private string NombreUsuarioField;
		private string PassField;
		private int idUsuarioField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get { return this.extensionDataField; }
			set { this.extensionDataField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.Nullable<bool> Activo
		{
			get { return this.ActivoField; }
			set { this.ActivoField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Nombre
		{
			get { return this.NombreField; }
			set { this.NombreField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string NombreUsuario
		{
			get { return this.NombreUsuarioField; }
			set { this.NombreUsuarioField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Pass
		{
			get { return this.PassField; }
			set { this.PassField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int idUsuario
		{
			get { return this.idUsuarioField; }
			set { this.idUsuarioField = value; }
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService1")]
	public interface IService1
	{
		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/obtenerUsuarios", ReplyAction = "http://tempuri.org/IService1/obtenerUsuariosResponse")]
		EjemploWCF.Usuarios[] obtenerUsuarios();

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/obtenerUsuarios", ReplyAction = "http://tempuri.org/IService1/obtenerUsuariosResponse")]
		System.Threading.Tasks.Task<EjemploWCF.Usuarios[]> obtenerUsuariosAsync();

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/verificarAcceso", ReplyAction = "http://tempuri.org/IService1/verificarAccesoResponse")]
		bool verificarAcceso(string user, string pass);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/verificarAcceso", ReplyAction = "http://tempuri.org/IService1/verificarAccesoResponse")]
		System.Threading.Tasks.Task<bool> verificarAccesoAsync(string user, string pass);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/insertarUsuario", ReplyAction = "http://tempuri.org/IService1/insertarUsuarioResponse")]
		void insertarUsuario(string user, string pass);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/insertarUsuario", ReplyAction = "http://tempuri.org/IService1/insertarUsuarioResponse")]
		System.Threading.Tasks.Task insertarUsuarioAsync(string user, string pass);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/eliminarUsuario", ReplyAction = "http://tempuri.org/IService1/eliminarUsuarioResponse")]
		void eliminarUsuario(string user);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/eliminarUsuario", ReplyAction = "http://tempuri.org/IService1/eliminarUsuarioResponse")]
		System.Threading.Tasks.Task eliminarUsuarioAsync(string user);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/desactivarUsuario", ReplyAction = "http://tempuri.org/IService1/desactivarUsuarioResponse")]
		bool desactivarUsuario(string user);

		[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/desactivarUsuario", ReplyAction = "http://tempuri.org/IService1/desactivarUsuarioResponse")]
		System.Threading.Tasks.Task<bool> desactivarUsuarioAsync(string user);
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
	{
		public Service1Client() { }

		public Service1Client(string endpointConfigurationName) : base(endpointConfigurationName) { }

		public Service1Client(string endpointConfigurationName, string remoteAddress) : base(endpointConfigurationName, remoteAddress) { }

		public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : base(endpointConfigurationName, remoteAddress) { }

		public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress) { }

		public EjemploWCF.Usuarios[] obtenerUsuarios()
		{
			return base.Channel.obtenerUsuarios();
		}

		public System.Threading.Tasks.Task<EjemploWCF.Usuarios[]> obtenerUsuariosAsync()
		{
			return base.Channel.obtenerUsuariosAsync();
		}

		public bool verificarAcceso(string user, string pass)
		{
			return base.Channel.verificarAcceso(user, pass);
		}

		public System.Threading.Tasks.Task<bool> verificarAccesoAsync(string user, string pass)
		{
			return base.Channel.verificarAccesoAsync(user, pass);
		}

		public void insertarUsuario(string user, string pass)
		{
			base.Channel.insertarUsuario(user, pass);
		}

		public System.Threading.Tasks.Task insertarUsuarioAsync(string user, string pass)
		{
			return base.Channel.insertarUsuarioAsync(user, pass);
		}

		public void eliminarUsuario(string user)
		{
			base.Channel.eliminarUsuario(user);
		}

		public System.Threading.Tasks.Task eliminarUsuarioAsync(string user)
		{
			return base.Channel.eliminarUsuarioAsync(user);
		}

		public bool desactivarUsuario(string user)
		{
			return base.Channel.desactivarUsuario(user);
		}

		public System.Threading.Tasks.Task<bool> desactivarUsuarioAsync(string user)
		{
			return base.Channel.desactivarUsuarioAsync(user);
		}
	}
}
